esphome:
  name: sofarme3000sp
  friendly_name: SOFARME3000SP

esp8266:
  board: nodemcuv2

# Enable logging
logger:
  level: WARN
  baud_rate: 0
  hardware_uart: UART1

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "SOFAR ME3000 Fallback Hotspot"
    password: !secret wifi_fallback

web_server:
  port: 80

font:
  - file: "gfonts://Roboto"
    id: font_top
    size: 16
  - file: "gfonts://Roboto"
    id: font_left
    size: 48
  - file: "gfonts://Roboto"
    id: font_right
    size: 20

image:
  - file: mdi:alert-outline
    id: alert
    resize: 80x80

i2c:
  sda: GPIO14
  scl: GPIO12
  scan: True
  id: bus_a
  frequency: 400kHz

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    lambda: |-
      it.printf(64, 0, id(font_top), TextAlign::TOP_CENTER, "State: %s", id(template_text_state_description).state.c_str());
      it.printf(0, 60, id(font_left), TextAlign::BASELINE_LEFT, "%.1fW", id(input_output_power).state);
      it.printf(127, 23, id(font_right), TextAlign::TOP_RIGHT , "%.1f%%", id(state_of_charge).state);
      it.printf(127, 36, id(font_right), TextAlign::BASELINE_RIGHT , "%.1fC", id(battery_temperature).state);
      it.printf(127, 60, id(font_right), TextAlign::BASELINE_RIGHT , "%.1fV", id(battery_voltage).state);

captive_portal:
uart:
  id: moduart
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  stop_bits: 1
  data_bits: 8
  parity: NONE

modbus:
  send_wait_time: 250ms
  uart_id: moduart
  id: modbus1
  flow_control_pin: GPIO5

modbus_controller:
  - id: mbc_5s
    address: 0x1
    modbus_id: modbus1
    command_throttle: 100ms
    setup_priority: -10
    update_interval: 5s
  - id: mbc_30s
    address: 0x1
    modbus_id: modbus1
    command_throttle: 400ms
    setup_priority: -10
    update_interval: 30s
  - id: mbc_300s
    address: 0x1
    modbus_id: modbus1
    command_throttle: 400ms
    setup_priority: -10
    update_interval: 300s

sensor:
  - platform: modbus_controller
    modbus_controller_id: mbc_30s
    name: "Running State"
    address: 0x0200
    register_type: "holding"
    value_type: U_WORD
    id: "sofarme3000sp_running_state"
    on_value:
      then:
       - text_sensor.template.publish:
           id: template_text_state_description
           state: !lambda |-
            static const std::map<int, const char*> state_lookup = {
              {0, "Wait"},
              {1, "Check"},
              {2, "Normal"},
              {3, "Check Discharge"},
              {4, "Discharge"},
              {5, "EPS"},
              {6, "Fault (temporary)"},
              {7, "Fault (permanent)"}
            };
            auto it = state_lookup.find(x);
            return it != state_lookup.end() ? it->second : "Unknown";
  - platform: modbus_controller
    modbus_controller_id: mbc_30s
    name: "Fault Message 1"
    address: 0x0201
    register_type: "holding"
    value_type: U_WORD
    icon: "mdi:alert-circle"
  - platform: modbus_controller
    modbus_controller_id: mbc_30s
    name: "Fault Message 2"
    address: 0x0202
    register_type: "holding"
    value_type: U_WORD
    icon: "mdi:alert-circle"
  - platform: modbus_controller
    modbus_controller_id: mbc_30s
    name: "Fault Message 3"
    address: 0x0203
    register_type: "holding"
    value_type: U_WORD
    icon: "mdi:alert-circle"
  - platform: modbus_controller
    modbus_controller_id: mbc_30s
    name: "Fault Message 4"
    address: 0x0204
    register_type: "holding"
    value_type: U_WORD
    icon: "mdi:alert-circle"
  - platform: modbus_controller
    modbus_controller_id: mbc_30s
    name: "Fault Message 5"
    address: 0x0205
    register_type: "holding"
    value_type: U_WORD
    icon: "mdi:alert-circle"
  - platform: modbus_controller
    modbus_controller_id: mbc_30s
    name: "Grid Voltage"
    address: 0x0206
    register_type: "holding"
    value_type: U_WORD
    filters:
      - multiply: 0.1
    device_class: voltage
    state_class: measurement
    unit_of_measurement: "V"
    accuracy_decimals: 2
  - platform: modbus_controller
    modbus_controller_id: mbc_30s
    name: "Grid Current"
    address: 0x0207
    register_type: "holding"
    value_type: S_WORD
    filters:
      - multiply: 0.01
    device_class: current
    state_class: measurement
    unit_of_measurement: "A"
    accuracy_decimals: 2
  - platform: modbus_controller
    modbus_controller_id: mbc_30s
    name: "Grid Frequency"
    address: 0x020c
    register_type: "holding"
    value_type: U_WORD
    filters:
      - multiply: 0.01
    device_class: frequency
    state_class: measurement
    unit_of_measurement: "Hz"
    accuracy_decimals: 2
  - platform: modbus_controller
    modbus_controller_id: mbc_30s
    name: "Battery Power"
    address: 0x020d
    register_type: "holding"
    value_type: S_WORD
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
    accuracy_decimals: 0
    filters:
      - multiply: 10
  - platform: modbus_controller
    modbus_controller_id: mbc_30s
    name: "Battery Voltage"
    id: "battery_voltage"
    address: 0x020e
    register_type: "holding"
    value_type: U_WORD
    filters:
      - multiply: 0.01
    device_class: voltage
    state_class: measurement
    unit_of_measurement: "V"
    accuracy_decimals: 2
  - platform: modbus_controller
    modbus_controller_id: mbc_30s
    name: "Battery Current"
    address: 0x020f
    register_type: "holding"
    value_type: S_WORD
    filters:
      - multiply: 0.01
    device_class: current
    state_class: measurement
    unit_of_measurement: "A"
    accuracy_decimals: 2
    icon: "mdi:current-dc"
  - platform: modbus_controller
    modbus_controller_id: mbc_30s
    name: "State of Charge"
    id: "state_of_charge"
    address: 0x0210
    register_type: "holding"
    value_type: U_WORD
    device_class: battery
    state_class: measurement
    unit_of_measurement: "%"
  - platform: modbus_controller
    modbus_controller_id: mbc_30s
    name: "Battery Temperature"
    id: "battery_temperature"
    address: 0x0211
    register_type: "holding"
    value_type: U_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement
  - platform: modbus_controller
    modbus_controller_id: mbc_5s
    name: "Feed Power"
    address: 0x0212
    register_type: "holding"
    value_type: S_WORD
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
    accuracy_decimals: 0
    filters:
      - multiply: 10
  - platform: modbus_controller
    modbus_controller_id: mbc_5s
    name: "Load Power"
    address: 0x0213
    register_type: "holding"
    value_type: U_WORD
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
    accuracy_decimals: 0
    filters:
      - multiply: 10
  - platform: modbus_controller
    modbus_controller_id: mbc_5s
    name: "Input/Output Power"
    id: "input_output_power"
    address: 0x0214
    register_type: "holding"
    value_type: S_WORD
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
    accuracy_decimals: 0
    filters:
      - multiply: 10
  - platform: modbus_controller
    modbus_controller_id: mbc_5s
    name: "Generation Power"
    address: 0x0215
    register_type: "holding"
    value_type: U_WORD
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
    accuracy_decimals: 0
    filters:
      - multiply: 10
  - platform: modbus_controller
    modbus_controller_id: mbc_30s
    name: "EPS Voltage"
    address: 0x0216
    register_type: "holding"
    value_type: U_WORD
    filters:
      - multiply: 0.1
    device_class: voltage
    state_class: measurement
    unit_of_measurement: "V"
    accuracy_decimals: 2
  - platform: modbus_controller
    modbus_controller_id: mbc_30s
    name: "EPS Power"
    address: 0x0217
    register_type: "holding"
    value_type: U_WORD
    device_class: power
    state_class: measurement
    unit_of_measurement: "W"
    accuracy_decimals: 0
    filters:
      - multiply: 10
  - platform: modbus_controller
    modbus_controller_id: mbc_300s
    name: "Energy Export (Day)"
    address: 0x0219
    register_type: "holding"
    value_type: U_WORD
    unit_of_measurement: "Wh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 0
    filters:
      - multiply: 10
    icon: "mdi:transmission-tower-export"
  - platform: modbus_controller
    modbus_controller_id: mbc_300s
    name: "Energy Import (Day)"
    address: 0x021a
    register_type: "holding"
    value_type: U_WORD
    unit_of_measurement: "Wh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 0
    filters:
      - multiply: 10
    icon: "mdi:transmission-tower-import"

  - platform: modbus_controller
    modbus_controller_id: mbc_300s
    name: "Energy Consumption (Day)"
    address: 0x021b
    register_type: "holding"
    value_type: U_WORD
    unit_of_measurement: "Wh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 0
    filters:
      - multiply: 10

  - platform: modbus_controller
    modbus_controller_id: mbc_30s
    name: "Total generation"
    address: 0x021c
    register_type: "holding"
    value_type: U_DWORD
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: mbc_30s
    name: "Total export"
    address: 0x021e
    register_type: "holding"
    value_type: U_DWORD
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 0
    icon: "mdi:transmission-tower-export"

  - platform: modbus_controller
    modbus_controller_id: mbc_30s
    name: "Total import"
    address: 0x0220
    register_type: "holding"
    value_type: U_DWORD
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 0
    icon: "mdi:transmission-tower-import"

  - platform: modbus_controller
    modbus_controller_id: mbc_30s
    name: "Total load consumption"
    address: 0x0222
    register_type: "holding"
    value_type: U_DWORD
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: mbc_300s
    name: "Energy Battery Charge (Day)"
    address: 0x0224
    register_type: "holding"
    value_type: U_WORD
    unit_of_measurement: "Wh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 0
    filters:
      - multiply: 10
    icon: "mdi:battery-plus-outline"

  - platform: modbus_controller
    modbus_controller_id: mbc_300s
    name: "Energy Battery Discharged (Day)"
    address: 0x0225
    register_type: "holding"
    value_type: U_WORD
    unit_of_measurement: "Wh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 0
    filters:
      - multiply: 10
    icon: "mdi:battery-minus-outline"

  - platform: modbus_controller
    modbus_controller_id: mbc_30s
    name: "Count Down Timer"
    address: 0x022a
    register_type: "holding"
    value_type: U_WORD
    state_class: measurement
    icon: "mdi:numeric"

  - platform: modbus_controller
    modbus_controller_id: mbc_30s
    name: "Inverter Alert Message"
    address: 0x022b
    register_type: "holding"
    value_type: U_WORD
    state_class: measurement
    icon: "mdi:alert-circle"
    on_value:
      then:
       - text_sensor.template.publish:
           id: template_text_inverter_alert_description
           state: !lambda |-
            std::string message="";
            int value=(int)x;
            if ((value & 1)) {
              message.append("ID81 ");
            }
            if ((value & 2)) {
              message.append("ID82 ");
            }
            if ((value & 4)) {
              message.append("ID83 ");
            }
            if ((value & 8)) {
              message.append("ID84 ");
            }
            if ((value & 128)) {
              message.append("ID85 ");
            }
            return message;

  - platform: modbus_controller
    modbus_controller_id: mbc_300s
    name: "Battery Cycles"
    address: 0x022c
    register_type: "holding"
    value_type: U_WORD
    state_class: total_increasing
    icon: "mdi:numeric"

  - platform: modbus_controller
    modbus_controller_id: mbc_30s
    name: "Inverter Temperature"
    address: 0x0238
    register_type: "holding"
    value_type: U_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement

  - platform: modbus_controller
    modbus_controller_id: mbc_30s
    name: "Inverter Heat Sink Temperature"
    address: 0x0239
    register_type: "holding"
    value_type: U_WORD
    unit_of_measurement: "°C"
    device_class: temperature
    state_class: measurement

text_sensor:
  - platform: template
    name: "Running State Description"
    id: template_text_state_description

  - platform: template
    name: "Inverter Alert Description"
    id: template_text_inverter_alert_description
